version: "3.8"

services:
  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - Redis_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Identity Service
  identity-service:
    build:
      context: ./identity-service
    env_file: ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - Redis_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Post Service
  post-service:
    build:
      context: ./post-service
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - Redis_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Media Service
  media-service:
    build:
      context: ./media-service
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - Redis_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Search Service
  search-service:
    build:
      context: ./search-service
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - Redis_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
